# Generated by Django 5.0 on 2023-12-10 15:13

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_encryptedfile_alter_user_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='encrypted_file',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(default=home.models.default_file, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
