# Generated by Django 5.0 on 2023-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_encryptedfile_file_encrypted_encryptedfile_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
